// Central icon registry. Importing only the names we use keeps the bundle
// small (Rollup tree-shakes @mdi/js and simple-icons to just these paths),
// so the list holds only what src/ references.

export {
  mdiThemeLightDark,
  mdiWeatherNight,
  mdiWhiteBalanceSunny,
  mdiChevronDown,
  mdiMagnify,
  mdiAccountOutline,
  mdiSourcePull,
  mdiTrayFull,
  mdiKeyboardOutline,
  mdiLogout,
  mdiConsoleLine,
  mdiViewGridOutline,
  mdiSourceRepository,
  mdiCurrencyUsd,
  mdiClipboardTextClockOutline,
  mdiCogOutline,
  mdiLogin,
  mdiContentCopy,
  mdiCheck,
  mdiChevronRight,
  mdiOpenInNew,
  mdiUnfoldMoreHorizontal,
  mdiTuneVariant,
  mdiProgressClock,
  mdiAlertCircleOutline,
  mdiGaugeFull,
  mdiDebugStepOver,
  mdiSwapHorizontal,
  mdiCancel,
  mdiSourceMerge,
  mdiLockOutline,
  mdiSourceBranchRemove,
  mdiFileDocumentEditOutline,
  mdiCircleOutline,
  mdiBugOutline,
  mdiChartBoxOutline,
  mdiScaleBalance,
  mdiCheckDecagramOutline,
  mdiFileDocumentOutline,
  mdiThumbUpOutline,
  mdiThumbDownOutline,
} from '@mdi/js';

import { siGithub } from 'simple-icons';

export const githubIcon = siGithub.path;
